apiVersion: v1
kind: Service
metadata: 
  name: reader-svc
  labels:
    tier: frontend-reader-svc
spec:
  type: NodePort
  ports:
  - port: 81
    targetPort: 5001
    nodePort: 30001    # 30000 - 32767
  selector:
    tier: frontend-reader-pod