apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  labels:
    tier: backend-db-pod
spec:
  containers:
  - name: db-container
    image: db-app:v1.0 
    ports:
    - containerPort: 5432
    env:
    - name: POSTGRES_USER
      value: postgres
    - name: POSTGRES_PASSWORD
      value: postgres