apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-dep
  labels:
    tier: backend-db-dep
spec:
  template:
    metadata:
      name: db-pod
      labels:
        tier: backend-db-pod
    spec:
      containers:
      - name: db-container
        image: db-app:v1.0 
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
  replicas: 1
  selector:
    matchLabels:
      tier: backend-db-pod
