apiVersion: apps/v1
kind: Deployment
metadata:
  name: writer-dep
  labels:
    tier: frontend-writer-dep
  annotations:
    # kubernetes.io/change-cause: "Initial deployment v1.0"
    kubernetes.io/change-cause: "Upgrade deployment v2.0"
spec:
  template:
    metadata:
      name: writer-pod
      labels:
        tier: frontend-writer-pod
    spec:
      containers:
      - name: writer-container
        image: writer-app:v2.0 
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_HOST
          value: db-app
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_USER
          value: postgres
        - name: DATABASE_PASSWORD
          value: postgres
        - name: DATABASE_NAME
          value: messagedb
        - name: DATABASE_TABLE_NAME
          value: message
        - name: WRITER_PORT
          value: "5000"
  replicas: 20
  selector:
    matchLabels:
      tier: frontend-writer-pod
  strategy:
    type: Recreate