apiVersion: apps/v1
kind: Deployment
metadata:
  name: reader-dep
  labels:
    tier: frontend-reader-dep
spec:
  template:
    metadata:
      name: reader-pod
      labels:
        tier: frontend-reader-pod
    spec:
      containers:
      - name: reader-container
        image: acrsamplewebapp.azurecr.io/reader-app:v1.0 
        ports:
        - containerPort: 5001
        env:
        - name: DATABASE_HOST
          value: db-svc
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_USER
          value: postgres
        - name: DATABASE_PASSWORD
          value: postgres
        - name: DATABASE_NAME
          value: messagedb
        - name: DATABASE_TABLE_NAME
          value: message
        - name: READER_PORT
          value: "5001"
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
  replicas: 1
  selector:
    matchLabels:
      tier: frontend-reader-pod

---

apiVersion: v1
kind: Service
metadata: 
  name: reader-svc
  labels:
    tier: frontend-reader-svc
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  selector:
    tier: frontend-reader-pod
