apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
stringData:
  DATABASE_USER: cG9zdGdyZXM=     #postgres
  DATABASE_PASSWORD: cG9zdGdyZXM= #postgres
  DATABASE_NAME: bWVzc2FnZWRi     #messagedb
  DATABASE_TABLE_NAME: bWVzc2FnZQ== #message

# Used: https://www.base64encode.org/